[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "text/javascript"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"